name = "app-page"
compatibility_date = "2024-06-14"
pages_build_output_dir = "./dist"

[[services]]
# ソースコードの中で参照する名前
# hono的には c.env.MY_WORKER_SERVICE のように参照する
binding = "MY_WORKER"
#binding = "MY_WORKER_BINDING"

# serviceは app-workerのwrangler.tomlにある `name` と同じ名前にする必要がある
service = "app-worker"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"